version: '2'
services:
    jhcontrolasistencia-app:
        image: jhcontrolasistencia
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhcontrolasistencia-mysql:3306/jhcontrolasistencia?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhcontrolasistencia-mysql:
        extends:
            file: mysql.yml
            service: jhcontrolasistencia-mysql
